version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /devset-ce-fe
    schedule: { interval: weekly }
    open-pull-requests-limit: 0
  - package-ecosystem: gradle
    directory: /devset-ce-be
    schedule: { interval: weekly }
    open-pull-requests-limit: 0
  - package-ecosystem: docker
    directory: /devset-ce-be
    schedule: { interval: weekly }