sonar.projectKey=devset-io_devset-ce
sonar.organization=devset-io

sonar.sources=devset-ce-be/src/main,devset-ce-fe/src
sonar.tests=devset-ce-be/src/test,devset-ce-fe/src

# Java backend
sonar.java.binaries=devset-ce-be/build/classes
sonar.java.source=25

# JS/TS frontend
sonar.javascript.lcov.reportPaths=devset-ce-fe/coverage/lcov.info

sonar.exclusions=**/build/**,**/dist/**,**/node_modules/**,landing-page/**