spring:
  datasource:
    url: jdbc:sqlite:file:config.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml